# Generated by Django 4.2 on 2023-04-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0002_alter_stu_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rName', models.CharField(max_length=100)),
                ('rAge', models.IntegerField()),
                ('page', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='stu',
        ),
    ]
