# Generated by Django 4.2 on 2023-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0003_books_delete_stu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
