# Generated by Django 4.2 on 2023-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0004_alter_books_rname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='page',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='rAge',
            field=models.IntegerField(null=True),
        ),
    ]
